travis:
  secure:
    BINSTAR_TOKEN: mlQlL6DrAr3k2xcNPYxAhSSSom9DbV//AIx/J0X0b+qSb0JID0D8CHV7kBrAbGkICxHBs5uWNHLODBBqRUJXEFqvm0VslDZg20esrq9oIS8ec0rq3no+6B8zE9P8F0rEhBNHIxU4Hj1Bv6Y0OJcY3nsgKvT3i0FbGlzFwEVMpfz3lKC30kV83mmoGdl5tT3P02NqskNtzpeRnk16LUj32aeNoyS4EENuVDVdor5f84VdLDx9RB9KWEqTd1Wbw6dxP1jwjzIRxtBcE5Brb+kw/VAtnlbMPBkbxgP6LcI5Ef+xOWX2p++aBAppP1sLDzjtuk3a/X9+mF1OPjnzPWsE6dqH6r+DzH9ngiLy+oUY1qwkF2mJS1jLlXjQhA3Q4SkyyrpwjVe+p7BfgzAMNvsg9NsZDznN9Z0yNVGEvISe6QlU1a4r+I6DeaWmkeFOM6B9Jo/7du+Nu15MpUlgy61thuoXtxfLP9YrM2h+rB6L2J79PC3sBtbr5skW6dQfPHFxfxrwoBXrnaaHvQUpq2mtH9ADFcZ9ZIpwe1jbZMO4tAAfKw//3XAFhqNPq+jiCcWwsQXRidBDOIEw8yBaMY9b775cpgsMV7A6Y9Qvp4HZupt28Vv18aCUb10k5rybcE35VRFF+zhQkR+zgKgiSF6j1GrZfRcOe83K0wd8aYChT2A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
